---

AZ_NAME: LAB 
OVERCOMMIT_RATIO:
  RAM: 1.5
  CPU: 6
DPDK:
  ENABLED: false 
CEPH:
  HOST: volume-production
  STORAGE_AZ: AZ1
  RBD_POOL: "{{ ceph.cinder.pool }}"
  RBD_USER: "{{ ceph.cinder.user }}"
