---

rules:
  - name: default
    class: hdd
    crush_map: default
    failure_domain_type: host
pools:
  - name: images
    pg: 8 
    rule: default
    application: rbd
    size: 3
    min_size: 2
  - name: volumes
    pg: 8 
    size: 3 
    min_size: 2
    rule: default
    application: rbd
  - name: gnocchi
    pg: 8 
    size: 3
    min_size: 2
    rule: default
    application: rbd
  - name: vms
    pg: 8 
    size: 3
    min_size: 2
    rule: default
    application: rbd
# dashboard username pass only need in ceph ver >=13
dashboard_username: admin
dashboard_password: 123qweA@123qweA@
users:
  - name: images
    permission: "mon 'allow r' osd 'allow class-read object_prefix rdb_children, allow rx, allow * pool=images'"
    services:
      - name: glance
        pool: images
  - name: volumes
    permission: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=vms, allow rwx pool=volumes, allow rwx pool=images'"
    services:
      - name: cinder
        pool: volumes
      - name: nova
        pool: vms
  - name: gnocchi
    permission: "mon 'allow r' osd 'allow class-read object_prefix rbd_children, allow rwx pool=gnocchi'"
    services:
      - name: gnocchi
        pool: gnocchi

ceph_conf_file:
    path: /tmp/ceph.base.01
    group: root
    owner: root
    mode: 640
ceph_parameters_file:
    path: /tmp/ceph.parameters.01
    group: root
    owner: root
    mode: 640
    
# if need to fix crush map, rules of pool. this variables are necessary

fix_crush_map: false
current_crush_tree_export: /tmp/1.txt
new_crush_tree_import: /tmp/2.txt
new_rules:
  - name: rep_first12 
    class: hdd
    crush_map: first12
    failure_domain_type: host
  - name: rep_last2
    class: hdd
    crush_map: last2 
    failure_domain_type: host
set_rule_of_pools:
  - name: images
    rule: rep_first12 
  - name: volumes
    rule: rep_first12
  - name: gnocchi
    rule: rep_last2
  - name: vms
    rule: rep_first12
