---

dbs:
  - name: keystone
    user: keystone
    passwd: "{{ keystone_env.KEYSTONE_DBPASS }}"
  - name: glance
    user: glance
    passwd: "{{ glance_env.GLANCE_DBPASS }}"
  - name: nova_api
    user: nova
    passwd: "{{ nova_env.NOVA_DBPASS }}"
  - name: nova
    user: nova
    passwd: "{{ nova_env.NOVA_DBPASS }}"
  - name: nova_cell0
    user: nova
    passwd: "{{ nova_env.NOVA_DBPASS }}"
  - name: neutron
    user: neutron
    passwd: "{{ neutron_env.NEUTRON_DBPASS }}"
  - name: cinder
    user: cinder
    passwd: "{{ cinder_env.CINDER_DBPASS }}"

# BAREMETAL
sql_cli: "mysql -uroot -p{{ mysql_env.openstack.MYSQL_ROOT_PASSWORD }} -e"
sql_cli_dbhandler: "mysql -uroot -p{{ mysql_env.openstack.MYSQL_ROOT_PASSWORD }} {{ database_name }} -e"

