---

- name: Install apt transport https
  apt: name=apt-transport-https state=present update_cache=yes

- name: Add filebeat apt key
  apt_key:
    url: "{{ filebeat_apt_key_url }}"
    state: present

- name: Add filebeat repo
  apt_repository:
    repo: "{{ filebeat_repo }}" 
    state: present
    update_cache: yes

- name: Install filebeat
  apt: name=filebeat state=present update_cache=yes

- name: Configure filebeat
  template: src=client.filebeat.yml.j2 dest=/etc/filebeat/filebeat.yml backup=yes

- name: Restart filebeat 
  service: name=filebeat state=restarted

- name: Enable filebeat
  service: name=filebeat enabled=yes 
