- name: remove container
  include_role:
    name: fixbugosd
    tasks_from: remove_container
  vars: 
    listcontainer: "{{item.split()[1]}}"
  when: inventory_hostname == "{{item.split()[0]}}"
  with_lines: "cat /tmp/output_{{inventory_hostname}}_osd"
- name: zap device
  include_role:
    name: fixbugosd
    tasks_from: zap_device
  vars: 
    listdevice: "{{item.split()[2]}}"
  when: inventory_hostname == "{{item.split()[0]}}"
  with_lines: "cat /tmp/output_{{inventory_hostname}}_osd"
- name: set fact osd die in each host
  include_role:
    name: fixbugosd
    tasks_from: retry_container
  vars: 
    newcontainer: "{{item.split()[1]}}"
    primarydisk: "{{item.split()[2]}}"
    waldisk: "{{item.split()[3]}}"
    dbdisk: "{{item.split()[4]}}"
  when: inventory_hostname == "{{item.split()[0]}}"
  with_lines: "cat /tmp/output_{{inventory_hostname}}_osd"
  
- name: wait osd up
  command: "docker logs {{item.name }}"
  register: result
  until: result.stderr.find('log_to_monitors') != -1
  failed_when: false
  retries: "{{retries_osd}}"
  delay: "{{delay_retries_osd}}"
  loop: "{{osd_nodes}}"

- name: check after fix
  include_role:
    name: fixbugosd
    tasks_from: main
