  - name: Set docker_registry_address
    set_fact:
      image_address: "{{docker_reg_host}}:{{docker_reg_port}}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
    when: docker_use_local_registry and clean_old_ceph
  - name: Set docker_registry_address
    set_fact:
      image_address: "{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
    when: not docker_use_local_registry and clean_old_ceph
    
  - name: zap devices
    docker_container:
      name: "ceph_zap"
      state: started
      image: "{{ image_address }}"
      volumes:
        - /dev/:/dev/
      env:
        OSD_DEVICE: "{{ listdevice }}"
      privileged: yes
      command: zap_device
    
  - name: delete ceph_zap docker container
    docker_container:
      name: "ceph_zap"
      state: absent
      image: "{{image_address}}"