---

- name: Ceph keyring setting 
  template: src=octavia.keyring.j2 dest="{{ docker_shared_conf_dir }}/glance/octavia/{{ octavia.glance.keyring_path }}" backup=yes

- name: Copy octavia base config for glance 
  template: src=octavia.base.j2 dest="{{ docker_shared_conf_dir }}/glance/octavia/octavia.conf" backup=yes

- name: Update octavia config for glance
  lineinfile:
    dest: "{{ docker_shared_conf_dir }}/glance/octavia/octavia.conf" 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^[client.{{ octavia.glance.user }}]', line: '[client.{{ octavia.glance.user }}]' }
    - { regexp: '^keyring', line: 'keyring = /etc/octavia/{{ octavia.glance.keyring_path }}' }

- name: Config octavia sudoer
  template: src=octavia.j2 dest="{{ docker_shared_conf_dir }}/glance/sudoers.d/octavia" backup=yes
