---

- name: Remove octavia containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - octavia-api
    - octavia-worker
    - octavia-health-manager
    - octavia-housekeeping

- include_role:
    name: octavia
    tasks_from: config

- name: Distribute octavia.conf to controllers not in hub group
  copy: src=/tmp/octavia.conf dest="{{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf"

- name: Change bind ip for octavia config
  shell: |
    sed -i "s|bind_host = {{ hostvars[groups['hub'][0]]['ansible_ssh_host'] }}|bind_host = {{ ansible_ssh_host }}|g" {{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf
    sed -i "s|bind_ip = {{ hostvars[groups['hub'][0]]['ansible_ssh_host'] }}|bind_ip = {{ ansible_ssh_host }}|g" {{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf

- name: Start octavia-api
  docker_container:
    name: octavia-api 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/octavia:{{ docker_images_tag }}.multivip"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: octavia 
    volumes:
      - "{{ docker_shared_conf_dir }}/octavia/:{{ docker_shared_conf_dir }}/octavia/"
      - /var/log/octavia:/var/log/octavia
      - /var/lib/octavia:/var/lib/octavia
      - /etc/localtime:/etc/localtime
    env: "{{ loadbalancer_env | merge({ 'OCTAVIA_START': 'START_OCTAVIA_API' }) }}"
    network_mode: host

- name: Start octavia-worker 
  docker_container:
    name: octavia-worker
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/octavia:{{ docker_images_tag }}.multivip"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: octavia
    volumes:
      - "{{ docker_shared_conf_dir }}/octavia/:{{ docker_shared_conf_dir }}/octavia/"
      - /var/log/octavia:/var/log/octavia
      - /var/lib/octavia:/var/lib/octavia
      - /etc/localtime:/etc/localtime
    env: "{{ loadbalancer_env | merge({ 'OCTAVIA_START': 'START_OCTAVIA_WORKER' }) }}"
    network_mode: host

- name: Start octavia-health-manager
  docker_container:
    name: octavia-health-manager
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/octavia:{{ docker_images_tag }}.multivip"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: octavia
    volumes:
      - "{{ docker_shared_conf_dir }}/octavia/:{{ docker_shared_conf_dir }}/octavia/"
      - /var/log/octavia:/var/log/octavia
      - /var/lib/octavia:/var/lib/octavia
      - /etc/localtime:/etc/localtime
    env: "{{ loadbalancer_env | merge({ 'OCTAVIA_START': 'START_OCTAVIA_HEALTH_MANAGER' }) }}"
    network_mode: host

- name: Start octavia-housekeeping 
  docker_container:
    name: octavia-housekeeping 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/octavia:{{ docker_images_tag }}.multivip"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: octavia
    volumes:
      - "{{ docker_shared_conf_dir }}/octavia/:{{ docker_shared_conf_dir }}/octavia/"
      - /var/log/octavia:/var/log/octavia
      - /var/lib/octavia:/var/lib/octavia
      - /etc/localtime:/etc/localtime
    env: "{{ loadbalancer_env | merge({ 'OCTAVIA_START': 'START_OCTAVIA_HOUSEKEEPING' }) }}"
    network_mode: host
