---

- include_role:
    name: sql
    tasks_from: update
  vars:
    db_update:
      name: octavia
      user: octavia
      passwd: "{{ loadbalancer_env.OCTAVIA_DBPASS }}"

- include_role:
    name: openstack-client
    tasks_from: user
  vars:
    domain:
      name: default
    service:
      user: octavia
      pass: "{{ octavia_pass }}"

- include_role:
    name: openstack-client
    tasks_from: service
  vars:
    domain_id: default
    region_name: "{{ loadbalancer_env.REGION_NAME }}" 
    service:
      type: load-balancer 
      name: octavia 
      user: octavia
      pass: "{{ octavia_pass }}"
      description: "OpenStack Load Balancer"
      endpoints:
        - scope: public
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9876'{% endraw %}"
        - scope: internal
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9876'{% endraw %}"
        - scope: admin
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9876'{% endraw %}"
