---

- set_fact: keypair_name="lbkey{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}"

- include_role:
    name: openstack-client
    tasks_from: keypair_delete
  vars:
    keypair:
      path: "{{ docker_shared_conf_dir }}/octavia/{{ keypair_name }}"
      name: "{{ keypair_name }}"

- include_role:
    name: openstack-client
    tasks_from: keypair
  vars:
    keypair:
      path: "{{ docker_shared_conf_dir }}/octavia/{{ keypair_name }}"
      name: "{{ keypair_name }}"

- name: Set amp ssh key 
  set_fact: amp_ssh_key_name="{{ keypair_name }}"

- include_role:
    name: openstack-client
    tasks_from: flavor_delete
  vars:
    flavor:
      name: "lb-flavor.{{ ansible_date_time.date }}"

- include_role:
    name: openstack-client
    tasks_from: flavor
  vars:
   flavor:
     name: "lb-flavor.{{ ansible_date_time.date }}"
     ram: 2048
     disk: 30
     vcpus: 2

- name: Set flavor
  set_fact: amp_flavor_id="{{ flavor_id.stdout }}"

- set_fact: secgrp_name="lb-mgmt-sec-grp.{{ ansible_date_time.date }}"

- include_role:
    name: openstack-client
    tasks_from: security_group_delete
  vars:
    security_group:
      name: "{{ secgrp_name }}"

- include_role:
    name: openstack-client
    tasks_from: security_group
  vars:
    security_group:
      name: "{{ secgrp_name }}"

- include_role:
    name: openstack-client
    tasks_from: security_group_add_rules
  vars:
    security_group:
      name: "{{ secgrp_name }}"
      rules:
        - "--protocol icmp"
        - "--protocol tcp --dst-port 22"
        - "--protocol tcp --dst-port 9443"

- name: Set security group 
  set_fact: amp_secgroup_list="{{ secgrp_id.stdout }}"

- name: Set network
  set_fact: amp_boot_network_list="{{ loadbalancer_env.AMP_BOOT_NETWORK_LIST }}"

- name: Get amphora image from repo
  get_url:
    url: "http://{{ docker_reg_ip }}/installer/openstack/amphora.qcow2"
    dest: /tmp/amphora.qcow2 

- include_role:
    name: openstack-client 
    tasks_from: glance_image_delete 
  vars:
    image:
      name: amphora-haproxy

- include_role:
    name: openstack-client
    tasks_from: glance_image
  vars:
    image:
      name: amphora-haproxy
      tag: "{{ loadbalancer_env.AMP_IMAGE_TAG }}"
      visibility: public
      disk_format: qcow2
      container_format: bare
      path: /tmp/amphora.qcow2
  
- name: Set image tag
  set_fact: amp_image_tag="{{ loadbalancer_env.AMP_IMAGE_TAG }}"

- name: Get list controller's IPs
  set_fact: controllers_ips=["{{ groups['controller'] | map('extract', hostvars, ['ansible_ssh_host']) | join('", "') }}"]

- name: Config octavia
  template: src="octavia.conf.j2" dest="{{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf" backup=yes
  when: octavia_env.SSL_ENABLED == 0

- name: Config octavia
  template: src="ssl.octavia.conf.j2" dest="{{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf" backup=yes
  when: octavia_env.SSL_ENABLED == 1 

- name: Fetch octavia.conf from hub to local
  fetch: src="{{ docker_shared_conf_dir }}/octavia/octavia/octavia.conf" dest=/tmp/octavia.conf flat=yes
