---

- include_role:
    name: sql
    tasks_from: drop 
  vars:
    db_update:
      name: octavia

- include_role:
    name: openstack-client
    tasks_from: service_delete
  vars:
    domain:
      name: default
    service:
      name: octavia

- include_role:
    name: openstack-client
    tasks_from: user_delete
  vars:
    service:
      user: octavia

- name: Remove octavia containers
  docker_container:
    name: "{{ item }}" 
    state: absent
  with_items:
    - octavia-bootstrap
    - octavia-api
    - octavia-worker
    - octavia-health-manager
    - octavia-housekeeping
  ignore_errors: yes
