---
  - name: Install MySQL
    apt: name={{ item }} cache_valid_time=3600 state=present
    with_items:
    - python-mysqldb
    - mariadb-server
  - name: Start the MySQL service
    service: 
      name: mysql
      state: started
      enabled: true
  - name: update config
    template: src={{item.src}} dest={{item.dest}}
    with_items:
      - { src: 'my.cnf.openstack.j2', dest: '/etc/mysql/mariadb.conf.d/99-openstack.cnf' }
  - name: Restart the MySQL service
    service:
      name: mysql
      state: restarted