---

#rings:
#  - ringnum: 0
#    bindnetaddr: 10.10.0.0 
#    broadcast: "yes"
#    mcastport: 5405
#    ttl: 1
#
#nodes:
#  - node_id: 1
#    hostname: controller01
#    addrs: 
#      - ringnum: 0 
#        value: 10.10.0.181
#  - node_id: 2 
#    hostname: controller02
#    addrs: 
#      - ringnum: 0 
#        value: 10.10.0.182
#  - node_id: 3 
#    hostname: controller03
#    addrs: 
#      - ringnum: 0
#        value: 10.10.0.183
#
#crm_params:
#  pe_warn_series_max: 1000
#  pe_input_series_max: 1000
#  pe_error_series_max: 1000
#  cluster_recheck_interval: 5min
#  stonith_enabled: false
