---

- name: Remove Glance containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - glance-api
    - glance-registry

- include_role:
    name: glance
    tasks_from: config

- name: Start Glance 
  docker_container:
    name: glance-api 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/glance:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: glance 
    volumes:
      - "{{ docker_shared_conf_dir }}/glance/:{{ docker_shared_conf_dir }}/glance/"
      - /var/log/glance:/var/log/glance
      - /var/lib/glance:/var/lib/glance
      - /etc/localtime:/etc/localtime
    env: "{{ image_env | merge({ 'GLANCE_START': 'START_GLANCE_API' }) }}"
    network_mode: host

- name: Start Glance
  docker_container:
    name: glance-registry 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/glance:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: glance
    volumes:
      - "{{ docker_shared_conf_dir }}/glance/:{{ docker_shared_conf_dir }}/glance/"
      - /var/log/glance:/var/log/glance
      - /var/lib/glance:/var/lib/glance
      - /etc/localtime:/etc/localtime
    env: "{{ image_env | merge({ 'GLANCE_START': 'START_GLANCE_REGISTRY' }) }}"
    network_mode: host
