---

- name: Check ha config for service
  shell: |
    cat {{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg | grep glance 
  register: service_cfg
  ignore_errors: yes
  
- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: glance_api
        port: 9292
        bind_ips:
        options:
  when: (service_cfg.rc == 1) and (glance_env.SSL_ENABLED == 0)

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: glance_api
        port: 9292
        bind_ips:
        options:
          - "mode tcp"
          - "option ssl-hello-chk"
  when: (service_cfg.rc == 1) and (glance_env.SSL_ENABLED == 1)

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: glance_registry
        port: 9191
        bind_ips:
        options:
  when: service_cfg.rc == 1
