---

- include_role:
    name: sql
    tasks_from: update
  vars:
    db_update:
      name: glance
      user: glance
      passwd: "{{ glance_env.GLANCE_DBPASS }}"

- include_role:
    name: openstack-client
    tasks_from: user
  vars:
    domain:
      name: default
    service:
      user: glance
      pass: "{{ glance_pass }}"

- include_role:
    name: openstack-client
    tasks_from: service
  vars:
    domain_id: default
    region_name: "{{ image_env.REGION_NAME }}" 
    service:
      type: image 
      name: glance 
      user: glance
      pass: "{{ glance_pass }}"
      description: "OpenStack Image"
      endpoints:
        - scope: public
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
        - scope: internal
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
        - scope: admin
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
  when: glance_env.SSL_ENABLED == 0 

- include_role:
    name: openstack-client
    tasks_from: service
  vars:
    domain_id: default
    region_name: "{{ image_env.REGION_NAME }}"
    service:
      type: image
      name: glance
      user: glance
      pass: "{{ glance_pass }}"
      description: "OpenStack Image"
      endpoints:
        - scope: public
          url: "{% raw %}'https://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
        - scope: internal
          url: "{% raw %}'https://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
        - scope: admin
          url: "{% raw %}'https://{{ general_env.CONTROLLER_HOST }}:9292'{% endraw %}"
  when: glance_env.SSL_ENABLED == 1 
