---

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/haproxy/"
    state: directory

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/haproxy/{{ item }}/"
    state: directory
  with_items:
    - backup
    - haproxy 

- name: Create haproxy log directory
  file:
    path: /var/log/haproxy/
    state: directory
    owner: syslog
    group: adm
    recurse: yes

- name: Configure haproxy
  template: src=haproxy.cfg.j2 dest="{{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg" backup=yes

- name: Set kernel parameters
  lineinfile:
    dest: /etc/sysctl.conf
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'net.ipv4.ip_forward', line: 'net.ipv4.ip_forward = 1' }
    - { regexp: 'net.ipv4.ip_nonlocal_bind', line: 'net.ipv4.ip_nonlocal_bind = 1' }

- name: Check sysctl
  shell: sysctl -p

- name: Update rsyslog config for haproxy
  template: src=rsyslog.conf.j2 dest=/etc/rsyslog.d/haproxy.conf backup=yes

- name: Restart rsyslog
  service:
    name: rsyslog 
    state: restarted
