---

- name: Create ceph secret directory
  file:
    path: /etc/ceph/
    state: directory
    owner: root
    group: root
    mode: 0775

- name: Ceph keyring setting for Compute Nodes
  template: src=client.key.j2 dest="{{ ceph.cinder.client.key_path }}" backup=yes

- name: Nova xml setting for Compute Nodes
  template: src=client.config.j2 dest="{{ ceph.cinder.client.config_path }}" backup=yes

- name: Virsh secret config
  shell: |
    virsh secret-undefine {{ ceph.cinder.rbd_secret_uuid }}
    virsh secret-define --file {{ ceph.cinder.client.config_path }}
    virsh secret-set-value --secret {{ ceph.cinder.rbd_secret_uuid }} --base64 $(cat {{ ceph.cinder.client.key_path }}) 
  ignore_errors: yes
