---

- name: Build OpenStack Client images
  docker_image:
    path: "{{ ops_dk_files_path }}/openstack-client"
    name: openstack-client
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/openstack-client"
    tag: "{{ docker_images_tag }}" 
    pull: no
    push: yes
    #nocache: yes
    buildargs: "{{ proxy }}"
