---

- name: Remove OpenStack client container
  docker_container:
    name: openstack-client 
    state: absent

- include_role:
    name: openstack-client 
    tasks_from: config

- name: Create OpenStack client 
  docker_container:
    name: openstack-client 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/openstack-client:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root 
    tty: yes 
    volumes:
      - "{{ docker_shared_conf_dir }}/openstack-client:{{ docker_shared_conf_dir }}/openstack-client"
      - /etc/localtime:/etc/localtime
    env: "{{ openstack_client_env }}"
    network_mode: host
  when: SSL_ENABLED == 0

- name: Create OpenStack client
  docker_container:
    name: openstack-client
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/openstack-client:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root
    tty: yes
    volumes:
      - "{{ docker_shared_conf_dir }}/openstack-client:{{ docker_shared_conf_dir }}/openstack-client"
      - /etc/localtime:/etc/localtime
    env: "{{ openstack_client_env_ssl }}"
    network_mode: host
  when: SSL_ENABLED == 1 

- name: Create OpenStack alias
  lineinfile:
    dest: ~/.bashrc 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: 'alias openstack', line: 'alias openstack="docker exec -ti openstack-client openstack"' }
