---

- name: Bootstrap Heat
  hosts: "{{groups[['controller'][0]}}"
  tasks:
    - include_role:
        name: aodh
        tasks_from: setup
  become: true

- name: Setup heat on Controller Nodes
  hosts: "{{groups[['controller'][0]}}"
  tasks:
    - include_role:
        name: aodh
        tasks_from: "{{ item }}"
      with_items:
        - controller
  become: true
