---

- name: Bootstrap ceilometer
  hosts: "{{groups[['controller'][0]}}"
  tasks:
    - include_role:
        name: ceilometer
        tasks_from: setup
  become: true

- name: Setup ceilometer on Controller Nodes
  hosts: "{{groups[['controller'][0]}}"
  tasks:
    - include_role:
        name: ceilometer
        tasks_from: "{{ item }}"
      with_items:
        - controller
  become: true