- name: rollback osds
  hosts: ceph
  #sudo: yes
  serial: 1
  tasks:
    - include_role: 
        name: ceph-rollback
        tasks_from: rollback-osds
      when: (ceph_new_version is defined) and upgrade_ceph and inventory_hostname in groups.ceph_osd
  become: true