---
- hosts: ceph
  tasks:
  - name: get list ceph backup container
    shell: |
      docker ps -a | grep backup | grep ceph| awk '{print $NF}'
    register: result_container_backup
    
  - name: clean ceph backup container
    docker_container:
      name: "{{item}}"
      state: absent
    loop: "{{ result_container_backup.stdout_lines }}"
  
  become: true
