- name: collect ceph version all
  hosts: ceph_conf
  tasks:
    - name: collect version monitors
      shell: "timeout 5 docker exec {{mon_name}} ceph versions " 
      register: result
      failed_when: false
      until: result.rc == 0
      retries: "{{retries_mon}}"
      delay: "{{delay_retries_mon}}"
      when: inventory_hostname in groups.ceph_mon

    - debug: msg="{{result.stdout}}"
  become: true