---
- hosts: ceph_mds
  tasks:
    - include_role: 
        name: ceph-mds
        tasks_from: install
      when: (parallel_create_mds is defined) and parallel_create_mds
  become: true
# neu ko lam parallel thi lam tung host mot
- hosts: ceph_mds
  serial: 1
  tasks:
    - include_role: 
        name: ceph-mds
        tasks_from: install
      when: (parallel_create_mds is defined) and not parallel_create_mds
  become: true

- hosts: ceph_mds[0]
  tasks:
    - include_role: 
        name: ceph-mds
        tasks_from: get_admin_key
  become: true

- hosts: ceph_mds[0]
  tasks:
    - include_role: 
        name: ceph-mds
        tasks_from: verify_mds
  become: true
  
- hosts: ceph_mds[0]
  tasks:
    - include_role: 
        name: ceph-mds
        tasks_from: create_fs
      when: (create_cephfs is defined) and create_cephfs
  become: true
