---

- import_playbook: memcached.yml 
- import_playbook: keepalived.yml 
- import_playbook: haproxy.yml 
- import_playbook: rabbitmq.yml 
- import_playbook: mysql-openstack.yml 
- import_playbook: mysql-gnocchi.yml 
- import_playbook: mysql-optimizer.yml
- import_playbook: redis.yml 
- import_playbook: zookeeper.yml
- import_playbook: etcd.yml
