---

- name: Clean gnocchi 
  hosts: controller
  tasks:
    - include_role:
        name: gnocchi
        tasks_from: teardown 
  become: true

- name: Create indexer databases
  hosts: controller
  tasks:
    - include_role:
        name: gnocchi 
        tasks_from: keepalived
    - include_role:
        name: gnocchi
        tasks_from: indexer
  become: true

- name: Bootstrap OpenStack projects
  hosts: controller:&hub
  tasks:
    - include_role:
        name: gnocchi 
        tasks_from: setup
  become: true

- name: Setup gnocchi on Controller Nodes 
  hosts: current_controller 
  tasks:
    - include_role:
        name: gnocchi 
        tasks_from: "{{ item }}"
      with_items:
        - controller 
        - haproxy
  become: true
