---

- name: Bootstrap OpenStack projects
  hosts: current_controller:&hub
  tasks:
    - include_role:
        name: horizon 
        tasks_from: otp.setup
  become: true

- name: Start other controllers
  hosts: current_controller
  tasks:
    - include_role:
        name: horizon 
        tasks_from: otp.controller
  become: true

- name: Update haproxy config
  hosts: current_controller
  tasks:
    - include_role:
        name: horizon 
        tasks_from: haproxy
  become: true
