---

- name: Setup neutron-ovs-agent on Compute Nodes
  hosts: current_compute:!ovs-dpdk
  tasks:
    - include_role:
        name: neutron
        tasks_from: "{{ item }}"
      vars:
        bridge_mappings:
          - network: dcn_net
            bridge: br-dcn
          - network: public_net
            bridge: br-public
      with_items:
        - neutron-openvswitch-agent
        - neutron-dhcp-agent
        - neutron-metadata-agent
  become: true
