---

- name: Bootstrap OpenStack projects
  hosts: current_controller:&hub
  tasks:
    - include_role:
        name: neutron 
        tasks_from: setup
      vars:
        bridge_mappings:
          - network: dcn_net
            bridge: br-dcn
          - network: public_net
            bridge: br-public
  become: true

- name: Setup neutron-server on Controller Nodes 
  hosts: current_controller
  tasks:
    - include_role:
        name: neutron 
        tasks_from: "{{ item }}"
      with_items:
        - neutron-server
        - haproxy
      vars:
        bridge_mappings:
          - network: dcn_net
            bridge: br-dcn
          - network: public_net
            bridge: br-public
  become: true
