---

- name: Install nova
  hosts: current_compute
  tasks:
    - include_role:
       name: nova
       tasks_from: compute
    - include_role:
        name: cinder
        tasks_from: compute
      when: ceph.nova.enabled == 1
    - include_role:
        name: nova
        tasks_from: ceph
      when: ceph.nova.enabled == 1
  become: true

- name: Discover new compute hosts
  hosts: hub 
  tasks:
    - include_role:
       name: controller
       tasks_from: discover_computes
  become: true
