---

- hosts: rabbitmq
  tasks:
  - include_role:
      name: rabbitmq
      tasks_from: "{{ item }}"
    with_items:
      - teardown #uninstall
      - package #install
      - add_openstack_user
  become: true