---

- hosts: current
  tasks:
    - name: Allow RSYNC for new super user without SUDO password
      lineinfile:
        path: /etc/sudoers
        state: present 
        line: "{{ user }} ALL=NOPASSWD: /usr/bin/rsync"
      vars:
        user: cloud
  become: true
