---

- name: Create openrc 
  hosts: localhost 
  tasks:
    - include_role:
        name: common 
        tasks_from: openrc 
      vars:
        OS_PROJECT_DOMAIN_NAME: Default 
        OS_USER_DOMAIN_NAME: Default
        OS_PROJECT_NAME: admin
        OS_TENANT_NAME: admin
        OS_USERNAME: admin
        OS_PASSWORD: "{{ keystone_pass }}"
        OS_AUTH_URL: "https://{{ services_controller }}:35357/v3"
        OS_IDENTITY_API_VERSION: 3
        OS_IMAGE_API_VERSION: 2
        OS_CACERT: "{{ docker_shared_conf_dir }}/openstack-client/openstack.crt"
  become: true
