---

- name: Fix apache2 baseline for docker registry
  hosts: docker-registry
  tasks:
    - include_role:
        name: baseline
        tasks_from: apache2
  become: true
  
- name: Fix baseline 
  hosts: all:!docker-registry
  tasks:
    - include_role:
        name: baseline
        tasks_from: main
      vars:
        baseline:
          users:
            - cloud
            - root
        profile:
          timeout: 300
        ssh_config:
          users:
            - cloud
            - nova
        nameservers:
          - 203.113.131.2
  become: true
