---

- name: Clean gnocchi 
  hosts: current_controller
  tasks:
    - docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - gnocchi-api
        - gnocchi-metricd
  become: true

- name: Setup gnocchi on Controller Nodes 
  hosts: current_controller 
  tasks:
    - include_role:
        name: gnocchi 
        tasks_from: "{{ item }}"
      with_items:
        - controller 
        - haproxy
  become: true
