---

- name: Postgres master 
  hosts: compute01
  tasks:
    - name: Remove old postgres container
      docker_container:
        name: "{{ item }}"
        state: absent
      with_items:
        - postgres
    
    - name: Remove old postgres data
      docker_volume:
        name: cluster-archives
        state: absent
      ignore_errors: yes
    
    - name: PostgreSQL 
      docker_container:
        name: postgres
        image: "{{ postgres.image }}"
        pull: yes
        restart_policy: unless-stopped
        state: started
        user: root 
        volumes:
          - cluster-archives:/var/cluster_archive
        env:
          INITIAL_NODE_TYPE: master
          NODE_ID: 1 
          NODE_NAME: compute01 
          CLUSTER_NODE_NETWORK_NAME: compute01 
          PGPASSWORD: Ybjk6z3y614UhG6m68hNPHY3Qx6XaDnE
          POSTGRES_PASSWORD: Ybjk6z3y614UhG6m68hNPHY3Qx6XaDnE
          POSTGRES_USER: postgres_user
          POSTGRES_DB: gnocchi
          CLUSTER_NODE_REGISTER_DELAY: 5
          REPLICATION_DAEMON_START_DELAY: 120
          CLUSTER_NAME: pg_cluster
          REPLICATION_DB: repl_db
          REPLICATION_USER: repl_user
          REPLICATION_PASSWORD: H5efRYlzkl41XZvt3mjXxufKxuKQEGxv
        network_mode: host
  become: true
