---

- name: Stop haproxy
  service:
    name: "{{ item }}" 
    state: stopped
  ignore_errors: yes
  with_items:
    - haproxy

- name: Cleanup haproxy
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/haproxy/ 
    - /var/lib/haproxy/

- name: Remove haproxy packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - haproxy
  ignore_errors: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
