---

- name: Stop keepalived
  service:
    name: "{{ item }}" 
    state: stopped
  ignore_errors: yes
  with_items:
    - keepalived

- name: Cleanup keepalived data 
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/keepalived/

- name: Remove keepalived packages
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  with_items:
    - keepalived
  ignore_errors: yes

- name: Remove useless packages from the cache
  apt:
    autoclean: yes

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
