---

- name: Get controllers ip list
  set_fact: ctl_ips=["{{ groups['controller'] | map('extract', hostvars, ['ansible_ssh_host']) | join('", "') }}"]

- name: Get controllers hostname
  set_fact: ctl_hostnames="{{ groups['controller'] }}"

- name: Set of controllers
  set_fact: controllers="{{ ctl_ips | get_hosts(ctl_hostnames) }}"

- name: Create haproxy config for new services
  template: src=haproxy.cfg.update.j2 dest=/tmp/haproxy.cfg.update backup=yes

- name: Update haproxy config 
  shell: |
    cat /tmp/haproxy.cfg.update >> /etc/haproxy/haproxy.cfg

- name: Restart haproxy
  service: name=haproxy state=restarted enabled=yes 
