- name: wait 30s for new rule effect, pool's pgs are relocating...
  pause:
    seconds: 30

- name: check current state
  include: get_map_osd_pool.yml
    
- name: ask for next action
  pause:
      prompt: " Do you want to wait next 30 sec, for pool's pgs relocate (yes/no)?"
  register: mypause
  delegate_to: localhost

- name: wait more
  include_role:
    name: ceph-fix-pool
    tasks_from: wait_effect
  when: (mypause.user_input is defined) and (mypause.user_input | bool)