---

common:
  private:
    ip: "{{ vip.haproxy.ip }}"
    inf: "{{ keepalived.haproxy.iface }}"
#  public:
#    ip: "{{ vip.public.ip }}" 
#    inf: "{{ vip.public.inf }}" 

ha_global:
  chroot: /var/lib/haproxy
  user: haproxy
  group: haproxy 
  maxconn: 4000
  stats_cnf:
    - opt: socket
      val: "/run/haproxy/admin.sock mode 660 level admin"
    - opt: timeout 
      val: 30s 

ha_defaults:
  mode: http
  options:
    - redispatch
    - httplog
    - forwardfor
  retries: 3
  timeout_cnf:
    - opt: http-request 
      val: 10s
    - opt: queue 
      val: 1m
    - opt: connect 
      val: 10s
    - opt: client 
      val: 1m
    - opt: server 
      val: 1m
    - opt: check 
      val: 10s

ha_frontend: 
  user: "{{ haproxy_env.USER }}" 
  pass: "{{ haproxy_env.PASS }}" 

ha_stats:
  ip: "{{ vip.haproxy.ip }}" 
  port: 1984
  mode: http
  stats_cnf: 
    - opt: enable
      val:
    - opt: uri
      val: "/"
    - opt: refresh
      val: 15s
    - opt: realm
      val: "Haproxy\\ Stats"
    - opt: auth
      val: "{{ ha_frontend.user }}:{{ ha_frontend.pass }}"

ha_services: 
  - name: keystone_internal
    port: 5000 
    bind_ips: 
    options: 
      - "http-request del-header X-Forwarded-Proto"   
  - name: keystone_admin
    port: 35357
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"
  - name: glance_api
    port: 9292
    bind_ips: 
    options:
  - name: glance_registry
    port: 9191
    bind_ips: 
    options:
  - name: nova_api
    port: 8774
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"
  - name: nova_placement_api
    port: 8778
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"
  - name: nova_metadata
    port: 8775
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"
  - name: nova_novncproxy
    port: 6080
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"
      - "http-request set-header X-Forwarded-Proto https if { ssl_fc }"
  - name: neutron_server
    port: 9696
    bind_ips: 
    options:
  - name: horizon
    port: 80
    bind_ips:
    options:
      - "balance source"
      - "http-request del-header X-Forwarded-Proto"
  - name: cinder_api
    port: 8776
    bind_ips: 
    options:
      - "http-request del-header X-Forwarded-Proto"

ha_bind_common_ips:
  - "{{ common.private.ip }}"

keepalived_conf: openstack.conf

keep_vrrp_scripts:
  - name: check_haproxy
    commands:
      - script "pkill -0 haproxy"
      - interval 2
      - weight 2

keep_vrrp_instances:
  - name: PRIVATE_V1 
    virtual_ipaddrs:
      - "{{ common.private.ip }}"
    cnf_params:  
      - param: state
        val: BACKUP 
      - param: priority
        val: "{{ keepalived.vrrp_prior }}"
      - param: advert_int
        val: 1
      - param: interface
        val: "{{ common.private.inf }}" 
      - param: virtual_router_id
        val: "{{ vip.haproxy.router_id }}" 

keep_vrrp_sync_grp:
  name: VG_1
  mems:
    - PRIVATE_V1
    - PUBLIC_V1
