# rename ceph-mon.backup.{{ceph_current_version}} -> ceph-mon and run ceph-mon
- name: rollback-mon
  shell:
    "docker rm -f {{item}} && docker container rename {{item}}.backup.{{ceph_current_version}} {{item}} && docker start {{item}}"
    
- name: make container has RestartPolicy unless-stopped
  command: "docker update --restart=unless-stopped {{item}}"
  
- name: check mon is up
  shell: "timeout 5 docker exec {{item}} ceph -s | grep 'mon:'| grep {{ansible_hostname}}" 
  changed_when: false
  register: check_mon
  failed_when: false
  until: check_mon.rc == 0
  retries: "{{retries_mon}}"
  delay: "{{delay_retries_mon}}"