- name: rollback mds
  shell:
    "docker rm -f {{item}} && docker container rename {{item}}.backup.{{ceph_current_version}} {{item}} && docker start {{item}}"

- name: make container has RestartPolicy unless-stopped
  command: "docker update --restart=unless-stopped {{item}}"
  
- name: check has active mds
  shell: "timeout 5 docker exec {{mon_name}} ceph -s" 
  changed_when: false
  register: check_mds
  failed_when: false
  until: check_mds.rc == 0 and not (check_mds.stdout is search('laggy or crashed'))
  retries: "{{retries_mds}}"
  delay: "{{delay_retries_mds}}"