- name: rollback mgr
  shell:
    "docker rm -f {{item}} && docker container rename {{item}}.backup.{{ceph_current_version}} {{item}} && docker start {{item}}"

- name: make container has RestartPolicy unless-stopped
  command: "docker update --restart=unless-stopped {{item}}"
  
- name: check has active mgr
  shell: "timeout 5 docker exec {{mon_name}} ceph -s | grep 'mgr:'" 
  changed_when: false
  register: check_mgr
  failed_when: false
  until: check_mgr.rc == 0 and not (check_mgr.stdout is search('no daemons active'))
  retries: "{{retries_mgr}}"
  delay: "{{delay_retries_mgr}}"