# - debug: msg={{listitem}}

- name: rollback-osd
  shell:
    "docker rm -f {{item}} && docker container rename {{item}}.backup.{{ceph_current_version}} {{item}} && docker start {{item}} && sleep 5s"


  
- name: make container has RestartPolicy unless-stopped
  command: "docker update --restart=unless-stopped {{item}}"
  
- name: wait osd up
  command: "docker logs {{item}}"
  register: result
  until: result.stderr.find('log_to_monitors') != -1
  retries: "{{retries_osd}}"
  delay: "{{delay_retries_osd}}"
  failed_when: false
  
- name: unset noout osd so the heath go normal
# (follow recommend in: https://ceph.com/geen-categorie/ceph-rolling-upgrades-with-ansible/)
  shell: timeout 5 docker exec {{item}} ceph osd unset noout
