- name: get localtion new container version
  set_fact:
    image_address: "{{docker_reg_host}}:{{docker_reg_port}}/{{ ceph_docker_image }}:{{ ceph_new_version }}"
  when: docker_use_local_registry 

- name: get localtion new container version
  set_fact:
    image_address: "{{ ceph_docker_image }}:{{ ceph_new_version }}"
  when: not docker_use_local_registry
  
- name: replace osd one-by-one
  include_role:
    name: ceph-upgrade
    tasks_from: upgrade_osd
  vars: 
    listitem: "{{ item }}"
  loop: "{{ osd_nodes }}"
  loop_control:
    pause: "{{osd_create_paused_time}}"
    
