---

- name: Remove Ceilometer containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - ceilometer-agent-central
    - ceilometer-agent-notification

- include_role:
    name: ceilometer
    tasks_from: config

- name: Start Ceilometer Agent Central
  docker_container:
    name: ceilometer-agent-central
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/ceilometer:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: ceilometer 
    volumes:
      - "{{ docker_shared_conf_dir }}/ceilometer/:{{ docker_shared_conf_dir }}/ceilometer/"
      - /var/log/ceilometer:/var/log/ceilometer
      - /var/lib/ceilometer:/var/lib/ceilometer
      - /etc/localtime:/etc/localtime
    env: "{{ data_collection_env | merge({ 'CEILOMETER_START': 'START_CEILOMETER_AGENT_CENTRAL' }) }}"
    network_mode: host

- name: Start Ceilometer Agent Notification
  docker_container:
    name: ceilometer-agent-notification 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/ceilometer:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: ceilometer
    volumes:
      - "{{ docker_shared_conf_dir }}/ceilometer/:{{ docker_shared_conf_dir }}/ceilometer/"
      - /var/log/ceilometer:/var/log/ceilometer
      - /var/lib/ceilometer:/var/lib/ceilometer
      - /etc/localtime:/etc/localtime
    env: "{{ data_collection_env | merge({ 'CEILOMETER_START': 'START_CEILOMETER_AGENT_NOTIFICATION' }) }}"
    network_mode: host
