---

- name: Create directory .ssh for nova user on Compute Node
  file:
    path: /var/lib/nova/.ssh
    state: directory
    owner: nova
    group: nova
    mode: 0775

- name: SSH private key for VM live migration
  copy:
    src: /usr/share/.ssh/id_rsa
    dest: /var/lib/nova/.ssh/id_rsa
    owner: nova
    group: nova
    mode: 0400

- name: SSH config files and public key for VM live migration
  copy:
    src: "/usr/share/.ssh/{{ item }}"
    dest: /var/lib/nova/.ssh/{{ item }}
    owner: nova
    group: nova
    mode: 0664
  with_items:
    - authorized_keys
    - id_rsa.pub

- name: Get list compute IPs
  set_fact: compute_ips=["{{ groups['compute'] | map('extract', hostvars, ['ansible_ssh_host']) | join('", "') }}"]

- name: Get list compute hostnames
  set_fact: compute_hosts="{{ groups['compute'] }}"

- name: Create compute dict with hostname and correspond IP
  set_fact: computes={{ compute_ips | get_hosts(compute_hosts) }}

- name: Auto add the fingerprint
  shell: |
    {% for ip, hostname in computes.items() %}sudo su - nova -c 'ssh-keyscan -H {{ ip }} >> /var/lib/nova/.ssh/known_hosts; ssh-keyscan -H {{ hostname }} >> /var/lib/nova/.ssh/known_hosts'; {% endfor %}

#- name: Hostkey checking false
#  copy:
#    src: config
#    dest: /var/lib/nova/.ssh/config
#    owner: nova
#    group: nova
#    mode: 0400
