---

- name: Remove neutron-dhcp-agent 
  docker_container:
    name: neutron-dhcp-agent 
    state: absent
  ignore_errors: yes

- include_role: 
    name: neutron
    tasks_from: config_dpdk

- name: Setup neutron-dhcp-agent
  docker_container:
    name: neutron-dhcp-agent 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/neutron:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: neutron
    volumes:
      - "{{ docker_shared_conf_dir }}/neutron/:{{ docker_shared_conf_dir }}/neutron/"
      - /var/log/neutron:/var/log/neutron
      - /var/lib/neutron:/var/lib/neutron
      - /etc/localtime:/etc/localtime
      - /run:/run:shared
    env: "{{ network_env | merge({ 'NEUTRON_START': 'START_NEUTRON_DHCP_AGENT' }) }}"
    network_mode: host
