---

- name: Create mysql data and log directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ MYSQL_CONTAINER_DATA_DIR }}"
    - "{{ MYSQL_CONTAINER_LOG_DIR }}"

- name: Create shared configuration directory
  file:
    path: "{{ MYSQL_CONTAINER_DATA_DIR }}/{{ item }}/"
    state: directory
  with_items:
    - data 
    - conf 

- name: Set mysql log permission
  file:
    path: "{{ MYSQL_CONTAINER_LOG_DIR }}"
    owner: 999 
    group: 999 

- name: Mysql config 
  template: src="{{ MYSQL_CONFIG_TEMPLATE }}" dest="{{ MYSQL_CONTAINER_DATA_DIR }}/conf/my.cnf" backup=yes
