---

- name: Add GlusterFS ppa repo
  apt_repository:
    repo: "{{ glusterfs_repo }}"
    state: present
    update_cache: yes

- name: Install GlusterFS server
  apt: name=glusterfs-server state=present update_cache=yes

- name: Config gluster peer
  shell: |
    {% for node in groups['glusterfs_server'] %}gluster peer probe {{ node }}{% if not loop.last %} && {% endif %}{% endfor %}

- name: Create brick
  file:
    path: "{{ gluster_brick }}"
    state: directory

- set_fact: gluster_1st_node="{{ groups['glusterfs_server'] | first }}"

- set_fact: num_of_glsrvs="{{ groups['glusterfs_server'] | length }}"

- name: Create volume when having more than 1 gluster server
  shell: |
    gluster volume create {{ gluster_volume }} replica {{ groups['glusterfs_server'] | length }} transport tcp {% for node in groups['glusterfs_server'] %}{{ node }}:{{ gluster_brick }}{% if not loop.last %} {% endif %}{% endfor %} force
    gluster volume start {{ gluster_volume }}
  when: (inventory_hostname == gluster_1st_node) and (num_of_glsrvs | int > 1)
  ignore_errors: yes

- name: Create volume when having only 1 gluster server
  shell: |
    gluster volume create {{ gluster_volume }} transport tcp {{ groups['glusterfs_server'] | first }}:{{ gluster_brick }} force
    gluster volume start {{ gluster_volume }}
  when: (inventory_hostname == gluster_1st_node) and (num_of_glsrvs | int == 1)
  ignore_errors: yes
