---

- name: Get management IP of target host
  set_fact: management_ip="{{ ansible_all_ipv4_addresses | ipaddr(management_net) | first }}"

- name: Get provider IP of target host
  set_fact: provider_ip="{{ ansible_all_ipv4_addresses | ipaddr(provider_net) | first }}"

- name: Copy shell to remote hosts
  copy: src=get_ifaces.sh dest=/tmp/get_ifaces.sh mode=0755

- name: Get all interfaces of remote hosts
  shell: /tmp/get_ifaces.sh
  register: result

- name: Get all interfaces name
  set_fact: ifaces="{{ result['stdout_lines'] }}"

- debug: var=ifaces
