---

- name: Get interfaces
  include_role:
    name: util_ifaces
    tasks_from: main

- name: Update new interfaces configuration
  template: src=interfaces.j2 dest=/tmp/interfaces backup=yes
