---

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/keepalived/"
    state: directory

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/keepalived/hosts/"
    state: directory

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/keepalived/hosts/scripts/"
    state: directory

- name: Configure keepalived
  template: src=keepalived.conf.base.j2 dest="{{ docker_shared_conf_dir }}/keepalived/keepalived.conf" backup=yes
