---

- name: Start keepalived 
  docker_container:
    name: keepalived
    image: "{{ keepalived_env.IMAGE }}"
    pull: yes
    capabilities:
      - NET_ADMIN 
    restart_policy: unless-stopped
    state: started
    command: /usr/sbin/keepalived -n -l -D -f /etc/keepalived/keepalived.conf -g /tmp/keepalived.log
    volumes:
      - "{{ docker_shared_conf_dir }}/keepalived/:/etc/keepalived/"
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/log/keepalived/:/tmp/
      - /etc/localtime:/etc/localtime
    env: "{{ keepalived_env }}"
    network_mode: host
