---

- name: Config /etc/network/interfaces 
  template: src=etc.network.interfaces.j2 dest="/etc/network/interfaces" backup=yes

- name: reboot system
  shell: |
    sleep 2
    init 6
  async: 1
  poll: 0
  when: reboot == 1

- name: Waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started delay={{ server_delay }} timeout={{ server_time_out }}
  when: reboot == 1

- name: Config vlan interfaces
  shell: |
    modprobe 8021q
    echo "8021q" >> /etc/modules
    {% for vlan in item.vlans %}
    vconfig add {{ item.name }} {{ vlan.id }}; ifconfig {{ item.name }}.{{ vlan.id }} {{ vlan.addr }} netmask {{ vlan.netmask }}
    {% endfor %}
  with_items: "{{ bonds.vlan }}"
