---

- name: Remove cluster containers
  docker_container:
    name: "{{ item }}" 
    state: absent
  with_items:
    - cluster

- name: Start cluster pacemaker & corosync
  docker_container:
    name: cluster
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/cluster:{{ docker_images_tag }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root 
    tty: yes
    volumes:
      - "{{ docker_shared_conf_dir }}/cluster/:{{ docker_shared_conf_dir }}/cluster/"
      - /var/log/pacemaker:/var/log/pacemaker
      - /var/log/corosync:/var/log/corosync
      - /var/lib/pacemaker:/var/lib/pacemaker
      - /var/lib/corosync:/var/lib/corosync
      - /etc/localtime:/etc/localtime
    env: "{{ ha_compute_env | merge({ 'CLUSTER_START': 'START_CLUSTER_SERVICES' }) }}"
    network_mode: host

- name: Waiting for cluster up and running
  shell: sleep 30

- name: Basic configuration for cluster
  shell: |
    docker exec -i cluster bash -c '{{ item }}'
  with_items:
    - "crm configure property stonith-enabled=false"
    - "crm configure property no-quorum-policy=ignore"
    - "crm configure property cluster-recheck-interval={{ general_env.RECHECK_INTERVAL }}"
  when: inventory_hostname in groups['hub']
