---

- name: Check crontab config
  shell: |
    grep -F '{{ crontab_line }}' /etc/crontab
  register: output 
  ignore_errors: yes

- name: Add crontab config 
  lineinfile:
    dest: /etc/crontab
    line: "{{ crontab_line }}" 
  when: output.rc == 1

- name: Restart cron service
  service:
    name: cron
    state: restarted
