---

- name: Build aodh images
  docker_image:
    path: "{{ ops_dk_files_path }}/aodh"
    name: aodh
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/aodh"
    tag: "{{ docker_images_tag }}"
    pull: no
    push: yes
    #nocache: yes
    buildargs: "{{ proxy }}"
