---

- name: Build Keystone, OpenStack Client, Horizon images
  docker_image:
    path: "~/{{ ops_dk_repo_dir }}/{{ item }}" 
    name: "{{ item }}" 
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/{{ item }}"
    tag: "{{ docker_images_tag }}" 
    push: yes
  with_items:
    - keystone
    - openstack-client
    - horizon

- name: Build Glance images
  docker_image:
    path: "~/{{ ops_dk_repo_dir }}/glance/{{ item }}"
    name: "{{ item }}"
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/{{ item }}"
    tag: "{{ docker_images_tag }}"
    push: yes
  with_items:
    - glance-api
    - glance-registry

- name: Build Nova images
  docker_image:
    path: "~/{{ ops_dk_repo_dir }}/nova/{{ item }}"
    name: "{{ item }}"
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/{{ item }}"
    tag: "{{ docker_images_tag }}"
    push: yes
  with_items:
    - nova-api
    - nova-conductor
    - nova-consoleauth
    - nova-novncproxy
    - nova-placement-api
    - nova-scheduler

- name: Build Neutron images
  docker_image:
    path: "~/{{ ops_dk_repo_dir }}/neutron/{{ item }}"
    name: "{{ item }}"
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/{{ item }}"
    tag: "{{ docker_images_tag }}"
    push: yes
  with_items:
    - neutron-server
    - neutron-dhcp-agent
    - neutron-metadata-agent
    - neutron-ovs-agent

- name: Build Cinder images
  docker_image:
    path: "~/{{ ops_dk_repo_dir }}/cinder/{{ item }}"
    name: "{{ item }}"
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/{{ item }}"
    tag: "{{ docker_images_tag }}"
    push: yes
  with_items:
    - cinder-api
    - cinder-scheduler
    - cinder-volume
