---

- name: Create proxy setting directory for docker registry
  file:
    path: /etc/systemd/system/docker.service.d/
    state: directory

- name: Proxy settings for docker registry
  template: src={{ item }} dest=/etc/systemd/system/docker.service.d/{{ item }}
  with_items:
    - http-proxy.conf
    - https-proxy.conf

- name: Reload daemon
  shell: |
    sudo systemctl daemon-reload
    sudo systemctl restart docker

- name: Remove old registry container 
  docker_container:
    name: "{{ docker_registry_name }}" 
    image: "{{ docker_registry_image }}" 
    state: absent

- name: Run docker registry container
  docker_container:
    expose: "{{ docker_registry_expose }}"
    image: "{{ docker_registry_image }}"
    name: "{{ docker_registry_name }}"
    ports: "{{ docker_registry_ports }}"
    pull: "{{ is_pull }}"
    restart_policy: always
    state: started 
    volumes:
      - /mnt/registry:/var/lib/registry
    env: 
      REGISTRY_HTTP_ADDR: 0.0.0.0:{{ docker_http_port }}
