---

- name: Ceph keyring setting 
  template: src=ceph.keyring.j2 dest="{{ docker_shared_conf_dir }}/gnocchi/ceph/{{ ceph.gnocchi.keyring_path }}" backup=yes

- name: Copy ceph base config for gnocchi 
  template: src=ceph.base.j2 dest="{{ docker_shared_conf_dir }}/gnocchi/ceph/ceph.conf" backup=yes

- name: Update ceph config for gnocchi
  lineinfile:
    dest: "{{ docker_shared_conf_dir }}/gnocchi/ceph/ceph.conf" 
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - { regexp: '^[client.{{ ceph.gnocchi.user }}]', line: '[client.{{ ceph.gnocchi.user }}]' }
    - { regexp: '^keyring', line: 'keyring = /etc/ceph/{{ ceph.gnocchi.keyring_path }}' }

- name: Config ceph sudoer
  template: src=ceph.j2 dest="{{ docker_shared_conf_dir }}/gnocchi/sudoers.d/ceph" backup=yes
