---

- name: Prepare keepalived track scripts for gnocchi_indexer 
  template: src=check_gnocchi_indexer.sh.j2 dest="{{ docker_shared_conf_dir }}/keepalived/hosts/scripts/check_gnocchi_indexer.sh" mode=0755 backup=yes

- include_role: 
    name: keepalived
    tasks_from: update
  vars:
    keepalived_conf: gnocchi_indexer.conf
    keep_vrrp_scripts:
      - name: check_gnocchi_indexer
        commands:
          - script "/etc/keepalived/hosts/scripts/check_gnocchi_indexer.sh"
          - interval 2
          - weight -30
    
    keep_vrrp_instances:
      - name: PRIVATE_GNOCCHI_INDEXDER
        auth:
          auth_type: "{{ vip.gnocchi_indexer.auth.auth_type }}"
          auth_pass: "{{ vip.gnocchi_indexer.auth.auth_pass }}"
        virtual_ipaddrs:
          - "{{ vip.gnocchi_indexer.ip }}"
        cnf_params:
          - param: state
            val: "{{ keepalived.gnocchi_indexer.state }}"
          - param: priority
            val: "{{ keepalived.gnocchi_indexer.vrrp_prior }}"
          - param: advert_int
            val: 1
          - param: interface
            val: "{{ keepalived.gnocchi_indexer.iface }}"
          - param: virtual_router_id
            val: "{{ vip.gnocchi_indexer.router_id }}"
    keep_vrrp_sync_grp:
      name: VG_1
      mems:
        - PRIVATE_GNOCCHI_INDEXDER
