---

networking:
  dhcp:
    enabled: false
    data:
      - interface: bond0
  static:
    enabled: true
    data:
      - interface: bond3.350
        address: 192.168.10.167
        netmask: 255.255.255.0
        gateway:
        nameservers:
        vlan:
          enabled: true
          vlan_raw_device: bond3
      - interface: bond3.400
        address: 192.168.20.167
        netmask: 255.255.255.0
        gateway:
        nameservers:
        vlan:
          enabled: true
          vlan_raw_device: bond3
  promisc:
    enabled: false
    data:
      - interface: bond1
      - interface: bond2
  bond:
    enabled: true
    data:
      manual:
        enabled: true
        data:
          - master: bond3
            slaves:
              - ens4f0
              - ens4f1
      promisc:
        enabled: false 
        data:
          - master: bond1
            slaves:
              - eno3
              - eno4
          - master: bond2
            slaves:
              - ens1f0
              - ens1f1

postgres_hostvars:
  NODE_ID: 2

zk_server:
  id: 2
  server: "{{ groups['zkcluster'][0] }}:2888:3888,0.0.0.0:2888:3888,{{ groups['zkcluster'][2] }}:2888:3888"

system_config:
  #reserved_mem: 
  reserved_mem: 65536
  cpu_set: 8-11,20-47  
  grub:
    default_hugepagesz: 1G
    hugepagesz: 1G 
    hugepages: 112 
    isolcpus: 4-11,16-47

dpdk_config:
  reserved_mem: 16384
  cpu_set: 6-11,14-23,30-35,38-47  
  grub:
    default_hugepagesz: 1G 
    hugepagesz: 1G 
    hugepages: 112 
    isolcpus: 2-11,14-23,26-35,38-47

libvirt_config:
  cpu_mode: custom
  cpu_model: Broadwell

OVS:
  DPDK_MEM_SEGMENTS: 256
  HUGEPAGE_MOUNT: /mnt/huge
  HUGEPAGE_MOUNT_PAGESIZE: '1G'
  NUM_HUGEPAGES: 56 
  SOCKET_MEM: 4096,4096
  MEM_CHANNELS: 12
  CORE_MASK: '0x3003000000'
  PMD_CORE_MASK: '0x3c00003c'
  INTERFACE_PRE_DRIVER: 'i40e'
  #INTERFACE_DRIVER: 'igb_uio'
  INTERFACE_DRIVER: 'vfio-pci'
  BOND_PORTS: 'bond1:eno5,bond1:eno6,bond2:ens1f0,bond2:ens1f1'
  BOND_MODE: 'bond1:balance-tcp,bond2:balance-tcp'
  BOND_LACP: 'bond1:active,bond2:active'
  BRIDGE_MAPPINGS: 'dcn_net:br-dcn,public_net:br-dpdk'
  DPDK_PORT_MAPPINGS: 'bond1:br-dcn,bond2:br-dpdk'
  DPDK_BIND_PORT: "False"
  TUNNEL_CIDR_MAPPING: ''
  PCI_MAPPINGS: ''
  EMC_SIZE: ''

# CEPH VARIABLES
#mon
mon_name: ceph-mon
mon_ip: 192.168.10.167
#mon_ip: 192.168.2.194

#mgr 
mgr_name: ceph-mgr

#osd
device_prepare:
  - name: sdb
    path: /dev/sdb
  - name: sdc
    path: /dev/sdc
  - name: sdd
    path: /dev/sdd
  - name: sde
    path: /dev/sde
  - name: sdf
    path: /dev/sdf
  - name: sdg
    path: /dev/sdg
  - name: sdh
    path: /dev/sdh
  - name: sdi
    path: /dev/sdi
  - name: sdj
    path: /dev/sdj
  - name: sdk
    path: /dev/sdk
  - name: sdl
    path: /dev/sdl
  - name: sdm
    path: /dev/sdm
  - name: sdn
    path: /dev/sdn
  - name: sdo
    path: /dev/sdo

osd_nodes:
  - name: ceph-osd-sdb
    primary_disk: /dev/sdb
  - name: ceph-osd-sdc
    primary_disk: /dev/sdc
  - name: ceph-osd-sdd
    primary_disk: /dev/sdd
  - name: ceph-osd-sde
    primary_disk: /dev/sde
  - name: ceph-osd-sdf
    primary_disk: /dev/sdf
  - name: ceph-osd-sdg
    primary_disk: /dev/sdg
  - name: ceph-osd-sdh
    primary_disk: /dev/sdh
  - name: ceph-osd-sdi
    primary_disk: /dev/sdi
  - name: ceph-osd-sdj
    primary_disk: /dev/sdj
  - name: ceph-osd-sdk
    primary_disk: /dev/sdk
  - name: ceph-osd-sdl
    primary_disk: /dev/sdl
  - name: ceph-osd-sdm
    primary_disk: /dev/sdm
  - name: ceph-osd-sdn
    primary_disk: /dev/sdn
  - name: ceph-osd-sdo
    primary_disk: /dev/sdo
