---

- name: Build base images
  docker_image:
    path: "{{ ops_dk_files_path }}/base"
    name: base 
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/base"
    tag: "{{ docker_images_tag }}"
    pull: no
    push: yes
    #nocache: yes
    buildargs: "{{ proxy }}"
