---

- name: Build Keystone image
  docker_image:
    path: "{{ ops_dk_files_path }}/keystone" 
    name: keystone 
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/keystone"
    tag: "{{ docker_images_tag }}" 
    pull: no
    push: yes
    #nocache: yes
    buildargs: "{{ proxy }}"
