---

- name: Remove old postgres container
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - postgres

- name: Remove old postgres data
  docker_volume:
    name: cluster-archives
    state: absent
  ignore_errors: yes

- name: PostgreSQL 
  docker_container:
    name: postgres
    image: "{{ postgres.image }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root 
    volumes:
      - cluster-archives:/var/cluster_archive
    env: "{{ postgres.env.master }}"
    network_mode: host
