---

- name: Remove old postgres data
  file:
    path: /var/lib/postgresql
    state: absent
  ignore_errors: yes

- name: Remove old postgres container
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - postgres

- name:  Create postgresql instance
  docker_container:
    name: postgres
    image: "{{ postgres_bdr.image }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root 
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    env: "{{ postgres_bdr.env }}"
    network_mode: host
