---

- name: Remove old postgres data
  file:
    path: /var/lib/postgresql-cluster 
    state: absent
  ignore_errors: yes

- name: Remove old postgres container
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - postgres

- name: PostgreSQL 
  docker_container:
    name: postgres
    image: "{{ postgres.image }}"
    pull: yes
    restart_policy: unless-stopped
    state: started
    user: root 
    volumes:
      - /var/lib/postgresql-cluster/data/master:/bitnami
    env: "{{ postgres.env.master }}"
    network_mode: host
