---

- include_role:
    name: postgres
    tasks_from: bdr_dropdb 

- include_role:
    name: postgres
    tasks_from: dropuser

- include_role:
    name: postgres
    tasks_from: inituser 

- include_role:
    name: postgres
    tasks_from: initdb 

- include_role:
    name: postgres
    tasks_from: bdr_replica
