- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
- name: install basic package
  apt:
    name: "{{ item}}
    state: latest
  with_items:
    - software-properties-common
    - python-pymysql