---

- name: Create shared configuration directory for masakari
  file:
    path: "{{ docker_shared_conf_dir }}/{{ item }}/"
    state: directory
  with_items:
    - masakari
    - masakarimonitors
    - pacemaker

- name: Create shared configuration directory for masakari-monitors
  file:
    path: "{{ docker_shared_conf_dir }}/masakari/{{ item }}/"
    state: directory
  with_items:
    - backup
    - masakari
    - sudoers.d
    - ssl

- name: Create shared masakarimonitors configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/masakarimonitors/{{ item }}/"
    state: directory
  with_items:
    - backup
    - masakarimonitors 
    - ssl

- name: Create shared pacemaker configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/pacemaker/{{ item }}/"
    state: directory
  with_items:
    - backup
    - pacemaker 

- name: Config masakari monitors 
  template: src=masakarimonitors.conf.j2 dest="{{ docker_shared_conf_dir }}/masakarimonitors/masakarimonitors/masakarimonitors.conf" backup=yes
  when: masakari_env.SSL_ENABLED == 0

- name: Config masakari monitors
  template: src=ssl.masakarimonitors.conf.j2 dest="{{ docker_shared_conf_dir }}/masakarimonitors/masakarimonitors/masakarimonitors.conf" backup=yes
  when: masakari_env.SSL_ENABLED == 1 

- name: Distribute pacemaker config from pacemaker cluster to compute node 
  copy: src=/usr/share/pacemaker/authkey dest="{{ docker_shared_conf_dir }}/pacemaker/pacemaker/authkey"

- name: Distribute certs
  copy: src="{{ playbook_dir }}/roles/openstack-client/files/{{ item }}" dest="{{ docker_shared_conf_dir }}/masakari/ssl/{{ item }}" backup=yes
  with_items:
    - openstack.crt
    - openstack.key
  when: masakari_env.SSL_ENABLED == 1

- name: Distribute certs
  copy: src="{{ playbook_dir }}/roles/openstack-client/files/{{ item }}" dest="{{ docker_shared_conf_dir }}/masakarimonitors/ssl/{{ item }}" backup=yes
  with_items:
    - openstack.crt
    - openstack.key
  when: masakari_env.SSL_ENABLED == 1
