---

- name: Create masakari database
  include_role:
    name: sql
    tasks_from: update
  vars:
    db_update:
      name: masakari
      user: masakari
      passwd: "{{ masakari_env.MASAKARI_DBPASS }}"

- name: Create service user
  include_role:
    name: openstack-client
    tasks_from: user
  vars:
    domain_id: default
    service:
      user: masakari
      pass: "{{ masakari_pass }}"

- name: Create service and service endpoints 
  include_role:
    name: openstack-client
    tasks_from: service 
  vars:
    domain_id: default
    region_name: North_VN
    service:
      type: ha
      name: masakari
      user: masakari
      pass: "{{ masakari_pass }}"
      description: "OpenStack Compute HA"
      endpoints:
        - scope: public
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:15868/v1/%(tenant_id)s'{% endraw %}"
        - scope: internal
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:15868/v1/%(tenant_id)s'{% endraw %}"
        - scope: admin
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:15868/v1/%(tenant_id)s'{% endraw %}"
