---

- name: Remove masakari-monitors 
  docker_container:
    name: masakari-monitors 
    state: absent

- include_role:
    name: masakari
    tasks_from: config_compute

- name: Run masakari-monitors 
  docker_container:
    name: masakari-monitors 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/masakari-monitors:{{ docker_images_tag }}"
    pull: yes
    state: started
    user: root 
    volumes:
      - "{{ docker_shared_conf_dir }}/masakari/:{{ docker_shared_conf_dir }}/masakari/"
      - "{{ docker_shared_conf_dir }}/masakarimonitors/:{{ docker_shared_conf_dir }}/masakarimonitors/"
      - "{{ docker_shared_conf_dir }}/pacemaker/:{{ docker_shared_conf_dir }}/pacemaker/"
      - /var/log/pacemaker:/var/log/pacemaker
      - /var/lib/pacemaker:/var/lib/pacemaker
      - /var/log/masakari:/var/log/masakari
      - /etc/localtime:/etc/localtime
    env: "{{ ha_compute_env | merge({ 'MASAKARI_START': 'START_MASAKARI_MONITORS' }) }}"
    network_mode: host
