---

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/horizon/"
    state: directory

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/horizon/{{ item }}/"
    state: directory
  with_items:
    - backup
    - openstack-dashboard 
    - apache2
    - ssl

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/horizon/apache2/conf-enabled/"
    state: directory

- name: Config apache2 
  template: src=openstack-dashboard.conf.j2 dest="{{ docker_shared_conf_dir }}/horizon/apache2/conf-enabled/openstack-dashboard.conf" backup=yes

- name: Config horizon 
  template: src=local_settings.py.j2 dest="{{ docker_shared_conf_dir }}/horizon/openstack-dashboard/local_settings.py" backup=yes
  when: dashboard_env.SSL_ENABLED == 0

- name: Config horizon (ssl)
  template: src=ssl.local_settings.py.j2 dest="{{ docker_shared_conf_dir }}/horizon/openstack-dashboard/local_settings.py" backup=yes
  when: dashboard_env.SSL_ENABLED == 1
