---

- name: Build Horizon image
  docker_image:
    path: "{{ ops_dk_files_path }}/horizon"
    name: horizon
    repository: "{{ docker_reg_host }}:{{ docker_host_port }}/horizon"
    tag: "{{ docker_images_tag }}" 
    pull: no
    push: yes
    #nocache: yes
    buildargs: "{{ proxy }}"
