---

- name: Install nova-compute
  apt: name={{ item }} state=present update_cache=yes
  with_items:
    - python-pymysql 
    - nova-compute

- name: Create nova ssl directory
  file:
    path: /etc/nova/ssl
    state: directory

- name: Distribute certs
  copy: src="{{ playbook_dir }}/roles/openstack-client/files/{{ item }}" dest="/etc/nova/ssl/{{ item }}" backup=yes
  with_items:
    - openstack.crt
    - openstack.key
  when: nova_env.SSL_ENABLED == 1

- name: Config nova-compute (without ceph config)
  template: src=nova.conf.j2 dest=/etc/nova/nova.conf backup=yes
  when: (ceph.nova.enabled == 0) and (nova_env.SSL_ENABLED == 0)

- name: Config nova-compute (with ceph config)
  template: src=nova.conf.ceph.j2 dest=/etc/nova/nova.conf backup=yes
  when: (ceph.nova.enabled == 1) and (nova_env.SSL_ENABLED == 0)

- name: Config nova-compute (without ceph config)
  template: src=ssl.nova.conf.j2 dest=/etc/nova/nova.conf backup=yes
  when: (ceph.nova.enabled == 0) and (nova_env.SSL_ENABLED == 1)

- name: Config nova-compute (with ceph config)
  template: src=ssl.nova.conf.ceph.j2 dest=/etc/nova/nova.conf backup=yes
  when: (ceph.nova.enabled == 1) and (nova_env.SSL_ENABLED == 1)

- name: Config libvirt for migration
  template: src=libvirtd.conf.j2 dest=/etc/libvirt/libvirtd.conf mode=0644 backup=yes

- name: Config libvirt_opts for migration
  template: src=libvirtd.j2 dest=/etc/default/libvirtd mode=0644 backup=yes

- name: Cleanup default setting
  shell: |
    virsh net-destroy default
    virsh net-undefine default
  ignore_errors: yes

- name: Restart compute services 
  service: name={{ item }} state=restarted
  with_items:
    - libvirtd
    - nova-compute

- name: Change nova shell
  shell: |
    usermod -s /bin/bash nova

- name: Configure ssh keys for VM live migration
  include_role:
    name: live_migration-ssh-cfg
    tasks_from: main 
