---

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/nova/"
    state: directory

- name: Create shared configuration directory
  file:
    path: "{{ docker_shared_conf_dir }}/nova/{{ item }}/"
    state: directory
  with_items:
    - backup
    - nova
    - apache2
    - ssl

- name: Config nova 
  template: src=nova.conf.ctl.j2 dest="{{ docker_shared_conf_dir }}/nova/nova/nova.conf" backup=yes
  when: nova_env.SSL_ENABLED == 0 

- name: Config nova
  template: src=ssl.nova.conf.ctl.j2 dest="{{ docker_shared_conf_dir }}/nova/nova/nova.conf" backup=yes
  when: nova_env.SSL_ENABLED == 1 

- name: Config nova-placement-api
  template: src=nova-placement-api.conf.j2 dest="{{ docker_shared_conf_dir }}/nova/apache2/nova-placement-api.conf" backup=yes

- name: Distribute certs
  copy: src="{{ playbook_dir }}/roles/openstack-client/files/{{ item }}" dest="{{ docker_shared_conf_dir }}/nova/ssl/{{ item }}" backup=yes
  with_items:
    - openstack.crt
    - openstack.key
  when: nova_env.SSL_ENABLED == 1
