---

- name: Remove Nova containers
  docker_container:
    name: "{{ item }}"
    state: absent
  with_items:
    - nova-api
    - nova-consoleauth
    - nova-scheduler
    - nova-placement-api
    - nova-novncproxy
    - nova-conductor

- include_role:
    name: nova
    tasks_from: config

- name: Start nova-api 
  docker_container:
    name: nova-api
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: nova
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/nova:/var/log/nova
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_API' }) }}"
    network_mode: host

- name: Start nova-consoleauth 
  docker_container:
    name: nova-consoleauth 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: nova
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/nova:/var/log/nova
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_CONSOLEAUTH' }) }}"
    network_mode: host

- name: Start nova-scheduler 
  docker_container:
    name: nova-scheduler 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: nova
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/nova:/var/log/nova
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_SCHEDULER' }) }}"
    network_mode: host

- name: Start nova-conductor 
  docker_container:
    name: nova-conductor
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: nova
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/nova:/var/log/nova
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_CONDUCTOR' }) }}"
    network_mode: host

- name: Start nova-novncproxy 
  docker_container:
    name: nova-novncproxy 
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: nova
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/nova:/var/log/nova
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_NOVNCPROXY' }) }}"
    network_mode: host

- name: Start nova placement
  docker_container:
    name: nova-placement-api
    image: "{{ docker_reg_host }}:{{ docker_host_port }}/nova:{{ docker_images_tag }}"
    pull: yes
    privileged: yes
    restart_policy: unless-stopped
    state: started
    user: root
    volumes:
      - "{{ docker_shared_conf_dir }}/nova/:{{ docker_shared_conf_dir }}/nova/"
      - /var/log/apache2:/var/log/apache2
      - /var/lib/nova:/var/lib/nova
      - /etc/localtime:/etc/localtime
    env: "{{ compute_env | merge({ 'NOVA_START': 'START_NOVA_PLACEMENT_API' }) }}"
    network_mode: host
