---

- name: Check ha config for nova-api 
  shell: |
    cat {{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg | grep nova_api 
  register: api_cfg
  ignore_errors: yes
  
- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_api
        port: 8774
        bind_ips:
        options:
          - "http-request del-header X-Forwarded-Proto"
  when: (api_cfg.rc == 1) and (nova_env.SSL_ENABLED == 0)

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_api
        port: 8774
        bind_ips:
        options:
          - "mode tcp"
          - "option ssl-hello-chk"
  when: (api_cfg.rc == 1) and (nova_env.SSL_ENABLED == 1)

- name: Check ha config for nova-placement-api 
  shell: |
    cat {{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg | grep nova_placement_api 
  register: placement_api_cfg 
  ignore_errors: yes

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_placement_api
        port: 8778
        bind_ips:
        options:
          - "http-request del-header X-Forwarded-Proto"
  when: placement_api_cfg.rc == 1

- name: Check ha config for nova-metadata 
  shell: |
    cat {{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg | grep nova_metadata 
  register: metadata_cfg
  ignore_errors: yes

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_metadata
        port: 8775
        bind_ips:
        options:
          - "http-request del-header X-Forwarded-Proto"
  when: metadata_cfg.rc == 1

- name: Check ha config for nova-novncproxy 
  shell: |
    cat {{ docker_shared_conf_dir }}/haproxy/haproxy/haproxy.cfg | grep nova_novncproxy 
  register: novncproxy_cfg
  ignore_errors: yes

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_novncproxy
        port: 6080
        bind_ips:
        options:
          - "http-request del-header X-Forwarded-Proto"
          - "http-request set-header X-Forwarded-Proto https if { ssl_fc }"
  when: (novncproxy_cfg.rc == 1) and (nova_env.SSL_ENABLED == 0)

- include_role:
    name: haproxy
    tasks_from: update
  vars:
    services:
      - name: nova_novncproxy
        port: 6080
        bind_ips:
        options:
          - "mode tcp"
          - "option ssl-hello-chk"
  when: (novncproxy_cfg.rc == 1) and (nova_env.SSL_ENABLED == 1)
