---

- include_role:
    name: sql
    tasks_from: drop 
  vars:
    db_update:
      name: nova_api

- include_role:
    name: sql
    tasks_from: drop
  vars:
    db_update:
      name: nova

- include_role:
    name: sql
    tasks_from: drop
  vars:
    db_update:
      name: nova_cell0 

- include_role:
    name: openstack-client
    tasks_from: service_delete
  vars:
    service:
      name: nova 

- include_role:
    name: openstack-client
    tasks_from: service_delete
  vars:
    service:
      name: placement 

- include_role:
    name: openstack-client
    tasks_from: user_delete
  vars:
    domain:
      name: default
    service:
      user: nova 

- include_role:
    name: openstack-client
    tasks_from: user_delete
  vars:
    service:
      user: placement 

- name: Remove nova containers
  docker_container:
    name: "{{ item }}" 
    state: absent
  with_items:
    - nova-api
    - nova-consoleauth
    - nova-scheduler
    - nova-conductor
    - nova-novncproxy
    - nova-placement-api
  ignore_errors: yes
