#$ ceph osd pool create cephfs_data <pg_num>
#$ ceph osd pool create cephfs_metadata <pg_num>
#$ ceph fs new <fs_name> <metadata> <data>
- name: create data pool
  shell: "docker exec {{mds_name}} ceph osd pool create {{data_pool_name}} {{pg_num}}"
- name: create metadata pool
  shell: "docker exec {{mds_name}} ceph osd pool create {{metadata_pool_name}} {{pg_num}}"
- name: create cephfs
  shell: "docker exec {{mds_name}} ceph fs new {{fs_name}} {{metadata_pool_name}} {{data_pool_name}}"

