- name: use image_address from local registry
  set_fact:
    image_address: "{{docker_reg_host}}:{{docker_reg_port}}/{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: docker_use_local_registry

- name: use image_address from extenal registry
  set_fact:
    image_address: "{{ ceph_docker_image }}:{{ ceph_docker_image_tag }}"
  when: not docker_use_local_registry
  
# docker run -d --net=host \
# -v /var/lib/ceph/:/var/lib/ceph/ \
# -v /etc/ceph:/etc/ceph \
# -e CEPHFS_CREATE=0 \
# ceph/daemon mds
- name: remove old mds if it has before
  docker_container:
    name: "{{mds_name}}"
    state: absent
  ignore_errors: yes
  when: mds_name is defined
  
- name: run docker with KV store
  docker_container:
    name: "{{ mds_name }}"
    state: started
    image: "{{ image_address }}"
    volumes:
      - /var/lib/ceph/:/var/lib/ceph/
      - /etc/localtime:/etc/localtime
      - /var/log/ceph:/var/log/ceph
    env:
      CEPH_PUBLIC_NETWORK: "{{ ceph_public_network }}"
      KV_TYPE: "{{ kv_type }}"
      KV_IP: "{{ kv_endpoint }}"
      KV_PORT: "{{kv_port}}"
      CEPHFS_CREATE: 0
    network_mode: host
    command: mds
    restart_policy: unless-stopped

- name: update permission log dir
  command: "docker exec {{mds_name}} chown -R ceph:ceph /var/log/ceph"
  ignore_errors: yes

- name: sleep 30s
  pause:
    seconds: 30

- name: restart docker
  command: "docker restart {{mds_name}}"
  ignore_errors: yes
