- name: check all mds is up
  shell: "timeout 5 docker exec {{mds_name}} ceph mds stat" 
  changed_when: false
  register: check_mds
  failed_when: false
  until: check_mds.rc == 0 and (mds_max == (check_mds.stdout | regex_search('[0-9]')| int) or check_mds.stdout is search('up:active') )
  retries: "{{retries_mds}}"
  delay: "{{delay_retries_mds}}"
- name: end execution
  fail:
    msg: "mds_max: {{mds_max}} is not fully up, manually verify "
  when: check_mds.stdout is defined and not (mds_max == (check_mds.stdout | regex_search('[0-9]')| int) or check_mds.stdout is search('up:active') )

# - debug:
#     msg: "mds status: {{check_mds.sdtout}}"
