---

- name: Get interfaces
  include_role:
    name: util_ifaces
    tasks_from: main

- name: Add telegraf apt key
  apt_key:
    url: "{{ telegraf_apt_key_url }}"
    state: present

- name: Add telegraf repo 
  apt_repository:
    repo: "{{ telegraf_repo }}" 
    state: present
    update_cache: yes

- name: Install telegraf
  apt: name=telegraf state=present update_cache=yes

- name: Add telegraf user to docker and haproxy groups
  user:
    name: telegraf 
    shell: /bin/bash
    group: docker
    append: yes

- name: Configure telegraf
  template: src=client.telegraf.conf.j2 dest=/etc/telegraf/telegraf.conf backup=yes

- name: Restart telegraf 
  service: name=telegraf state=restarted
