---

- name: Create heat database
  include_role:
    name: sql
    tasks_from: update
  vars:
    db_update:
      name: heat
      user: heat
      passwd: "{{ heat_env.HEAT_DBPASS }}"

- name: Create service user
  include_role:
    name: openstack-client
    tasks_from: user
  vars:
    domain:
      name: default
    service:
      user: heat
      pass: "{{ heat_pass }}"

- name: Create heat and heat endpoints
  include_role:
    name: openstack-client
    tasks_from: service
  vars:
    domain_id: default
    region_name: "{{ orchestration_env.REGION_NAME }}"
    service:
      type: orchestration 
      name: heat
      user: heat
      pass: "{{ heat_pass }}"
      description: "Orchestration"
      endpoints:
        - scope: public
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8004/v1/%(tenant_id)s'{% endraw %}"
        - scope: internal
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8004/v1/%(tenant_id)s'{% endraw %}"
        - scope: admin
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8004/v1/%(tenant_id)s'{% endraw %}"

- name: Create heat-cfn and heat-cfn endpoints
  include_role:
    name: openstack-client
    tasks_from: service
  vars:
    domain_id: default
    region_name: "{{ orchestration_env.REGION_NAME }}"
    service:
      type: cloudformation 
      name: heat-cfn
      user: heat
      pass: "{{ heat_pass }}"
      description: "Orchestration"
      endpoints:
        - scope: public
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8000/v1'{% endraw %}"
        - scope: internal
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8000/v1'{% endraw %}"
        - scope: admin
          url: "{% raw %}'http://{{ general_env.CONTROLLER_HOST }}:8000/v1'{% endraw %}"

- name: Create heat domain
  include_role:
    name: openstack-client
    tasks_from: domain 
  vars:
    domain:    
      name: heat
      description: "Stack projects and users"

- name: Create heat_domain_admin user
  include_role:
    name: openstack-client
    tasks_from: user
  vars:
    domain:
      name: heat
    service:
      user: heat_domain_admin 
      pass: "{{ heat_domain_admin_pass }}"

- name: Add admin role to the heat_domain_admin user in the heat domain
  include_role:
    name: openstack-client
    tasks_from: role_assignment 
  vars:
    domain:
      name: heat
      user_domain: heat
      user: heat_domain_admin
    role: admin 

- name: Create new roles
  include_role:
    name: openstack-client
    tasks_from: role_create 
  vars:
    roles: 
      - heat_stack_owner
      - heat_stack_user
